function figure1 = createfigure4(X1, Y1)
%CREATEFIGURE4(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Mar-2017 11:54:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create title
title('$$c(x) = 6e^{9x-4}$$','FontSize',20,'Interpreter','latex');

% Create xlabel
xlabel('x','Interpreter','latex','FontSize',20);

% Create ylabel
ylabel('c(x)','Interpreter','latex','FontSize',20);
end

