function figure1 = createfigure3(X1, YMatrix1)
%CREATEFIGURE2(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Mar-2017 11:39:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineStyle','none');
set(plot1(1),'Marker','+','Color',[0 1 0],...
    'DisplayName','a(x) = 4log_5(9x-2)');
set(plot1(2),'Marker','*','Color',[1 0 0],...
    'DisplayName','b(x) = cos(4(log_6(2x+3))) + sen(2(log_6(2x+5)))');

% Create xlabel
xlabel('x','Interpreter','latex','FontSize',15);

% Create ylabel
ylabel('y','Interpreter','latex','FontSize',15);

% Create title
title('Funciones a(x) y b(x)','FontSize',20,'FontName','High Tower Text');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.617078993055554 0.528362014021668 0.274088541666667 0.137667304015296],...
    'FontSize',15,...
    'FontName','High Tower Text');
end