function figure1 = createfigure5(X1, Y1)
%CREATEFIGURE4(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Mar-2017 11:50:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'YMinorGrid','on');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create semilogy
semilogy(X1,Y1);

% Create xlabel
xlabel('$$log(x)$$','Interpreter','latex','FontSize',15);

% Create ylabel
ylabel('$$c(x)$$','Interpreter','latex','FontSize',15);

% Create title
title('$$c(x) = 6e^{9x-4}$$','Interpreter','latex','FontSize',20);
end

