function figure1 =  createfigure2(X1, Y1)
%CREATEFIGURE2(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Mar-2017 11:46:58

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Marker','*','LineStyle','none','Color',[1 0 0]);

% Create title
title('$$b(x) = cos(4(log_6(2x+3)))+sen(2(log_6(2x+5)))$$',...
    'Interpreter','latex',...
    'FontSize',20);

% Create xlabel
xlabel('$$x$$','Interpreter','latex','FontSize',15);

% Create ylabel
ylabel('$$b(x)$$','Interpreter','latex','FontSize',15);
end